name: github-actions-demo
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v



image: python

stages:
    - build
    - test
    - deploy

build-job:
    stage: build
    script:
        - python3 -V

test-count:
    stage: test
    script:
        - python3 sum.py

deploy-job:
    stage: deploy
    script:
        - echo "terminou :D"
